version: '3.8'
services:
    build:
        build:
            context: .
            dockerfile: build-Dockerfile
        environment:
            TEAMCITY_VERSION: 1.2.3
            Git_Branch: main
        volumes:
            - C:/temp/artifacts:C:/artifacts
            - ../:C:/build
    amazon:
        build:
            context: .
            dockerfile: amazon-Dockerfile
        environment:
            TEAMCITY_VERSION: 1.2.3
        volumes:
            - C:\Temp\artifacts\Sashimi.Terraform.Tests:/artifacts
    centos:
        build:
            context: .
            dockerfile: centOS-Dockerfile
        environment:
            TEAMCITY_VERSION: 1.2.3
        volumes:
            - C:\Temp\artifacts\Sashimi.Terraform.Tests:/artifacts
    debian:
        build:
            context: .
            dockerfile: debian-Dockerfile
        environment:
            TEAMCITY_VERSION: 1.2.3
        volumes:
            - C:\Temp\artifacts\Sashimi.Terraform.Tests:/artifacts
    fedora:
        build:
            context: .
            dockerfile: fedora-Dockerfile
        environment:
            TEAMCITY_VERSION: 1.2.3
        volumes:
            - C:\Temp\artifacts\Sashimi.Terraform.Tests:/artifacts
    opensuse:
        build:
            context: .
            dockerfile: openSUSE-Dockerfile
        environment:
            TEAMCITY_VERSION: 1.2.3
        volumes:
            - C:\Temp\artifacts\Sashimi.Terraform.Tests:/artifacts
    rhel:
        build:
            context: .
            dockerfile: rhel-Dockerfile
        environment:
            TEAMCITY_VERSION: 1.2.3
        volumes:
            - C:\Temp\artifacts\Sashimi.Terraform.Tests:/artifacts
    sles:
        build:
            context: .
            dockerfile: sles-Dockerfile
        environment:
            TEAMCITY_VERSION: 1.2.3
        volumes:
            - C:\Temp\artifacts\Sashimi.Terraform.Tests:/artifacts
    ubuntu18:
        build:
            context: .
            dockerfile: ubuntu18-Dockerfile
        environment:
            TEAMCITY_VERSION: 1.2.3
        volumes:
            - C:\Temp\artifacts\Sashimi.Terraform.Tests:/artifacts
    ubuntu20:
        build:
            context: .
            dockerfile: ubuntu20-Dockerfile
        environment:
            TEAMCITY_VERSION: 1.2.3
        volumes:
            - C:\Temp\artifacts\Sashimi.Terraform.Tests:/artifacts
