version: '3.8'

x-linux-test-defaults: &linux-test-defaults
    platform: linux
    depends_on:
        - build
    volumes:
        - ../publish:/publish
    environment:
        AWS_E2E_AccessKeyId:
        AWS_E2E_SecretKeyId:
        Azure_OctopusAPITester_ClientId:
        Azure_OctopusAPITester_Password:
        Azure_OctopusAPITester_SubscriptionId:
        Azure_OctopusAPITester_TenantId:

services:
    build:
        platform: windows
        build:
            context: .
            dockerfile: build-Dockerfile
        volumes:
            - ../:C:/repoRoot
        environment:
            TEAMCITY_VERSION:
            Git_Branch:
    amazon:
        <<: *linux-test-defaults
        build:
            context: .
            dockerfile: amazon-Dockerfile
    centos:
        <<: *linux-test-defaults
        build:
            context: .
            dockerfile: centOS-Dockerfile
    debian:
        <<: *linux-test-defaults
        build:
            context: .
            dockerfile: debian-Dockerfile
    fedora:
        <<: *linux-test-defaults
        build:
            context: .
            dockerfile: fedora-Dockerfile
    opensuse:
        <<: *linux-test-defaults
        build:
            context: .
            dockerfile: openSUSE-Dockerfile
    rhel:
        <<: *linux-test-defaults
        build:
            context: .
            dockerfile: rhel-Dockerfile
    sles:
        <<: *linux-test-defaults
        build:
            context: .
            dockerfile: sles-Dockerfile
    ubuntu18:
        <<: *linux-test-defaults
        build:
            context: .
            dockerfile: ubuntu18-Dockerfile
    ubuntu20:
        <<: *linux-test-defaults
        build:
            context: .
            dockerfile: ubuntu20-Dockerfile